Repository laminas/laminas-filter, pull requests merged in 2021-11, with the labels that each got.

#37 Removed zendframework bridge dependency
  composer.json
  composer.lock
Labels: Enhancement, dependencies

#38 Fixed broken anchors in docs
  docs/book/standard-filters.md
Labels: Bug, Documentation

#39 Adds call-outs for new and deprecated features of version 2.12.0
  docs/book/standard-filters.md
Labels: Documentation, Enhancement
