Repository laminas/laminas-filter, pull requests merged in 2022-07, with the labels that each got.

#52 Improve type inference for the filter plugin manager
  composer.json
  composer.lock
  psalm-baseline.xml
  psalm.xml.dist
  src/FilterChain.php
  src/FilterPluginManager.php
  src/FilterPluginManagerFactory.php
  src/Inflector.php
  src/StaticFilter.php
  src/StringToUpper.php
  src/Word/Service/SeparatorToSeparatorFactory.php
  test/FilterPluginManagerFactoryTest.php
  test/FilterPluginManagerTest.php
  test/StaticAnalysis/PluginRetrievalTest.php
  test/StaticFilterTest.php
Labels: Documentation, Enhancement

#54 Remove trailing spaces in Readme
  README.md
Labels: Documentation

#59 Drop support for Service Manager 2.x series
  composer.json
  composer.lock
  psalm-baseline.xml
  src/FilterPluginManager.php
  test/Compress/TarLoadArchiveTarTest.php
  test/FilterChainTest.php
Labels: dependencies

#60 servicemanager is required - don't suggest it anymore
  composer.json
Labels: Documentation, Enhancement

#62 Update Psalm to 4.24.0
  composer.json
  composer.lock
  src/ConfigProvider.php
  src/File/LowerCase.php
  src/FilterPluginManager.php
  src/StringToLower.php
Labels: Documentation, Enhancement
