Repository laminas/laminas-filter, pull requests merged in 2022-11, with the labels that each got.

#73 Deprecate Encryption Related Filters and Adapters
  psalm-baseline.xml
  src/Decrypt.php
  src/Encrypt.php
  src/Encrypt/BlockCipher.php
  src/Encrypt/EncryptionAlgorithmInterface.php
  src/Encrypt/Openssl.php
  src/File/Decrypt.php
  src/File/Encrypt.php
  test/Encrypt/BlockCipherTest.php
  test/Encrypt/OpensslTest.php
  test/Encrypt/openssl/private_encrypted_2048.pem
  test/Encrypt/openssl/private_encrypted_4096.pem
  test/Encrypt/openssl/private_unencrypted_2048.pem
  test/Encrypt/openssl/private_unencrypted_4096.pem
  test/Encrypt/openssl/public_2048.pem
  test/Encrypt/openssl/public_4096.pem
  test/EncryptTest.php
Labels: Bug, Enhancement, Feature Removal

#76 Minor SA improvements to compression related filters
  psalm-baseline.xml
  src/Compress/AbstractCompressionAlgorithm.php
  src/Compress/Bz2.php
  src/Compress/Gz.php
  src/Compress/Tar.php
  src/Compress/Zip.php
  src/Exception/ExceptionInterface.php
Labels: Documentation, Enhancement

#77 General SA Improvements & Low-Hanging Fruit
  README.md
  composer.json
  composer.lock
  psalm-baseline.xml
  src/AbstractDateDropdown.php
  src/AbstractFilter.php
  src/AbstractUnicode.php
  src/BaseName.php
  src/Boolean.php
  src/Compress.php
  src/Compress/AbstractCompressionAlgorithm.php
  src/DataUnitFormatter.php
  src/DateTimeFormatter.php
  src/Digits.php
  src/Dir.php
  src/HtmlEntities.php
  src/Inflector.php
  src/PregReplace.php
  src/RealPath.php
  src/StringPrefix.php
  src/StringSuffix.php
  src/StringToLower.php
  src/StringToUpper.php
  src/StringTrim.php
  src/ToFloat.php
  src/ToInt.php
  src/ToNull.php
  src/UpperCaseWords.php
  src/Word/AbstractSeparator.php
  src/Word/CamelCaseToSeparator.php
  src/Word/DashToSeparator.php
  src/Word/SeparatorToCamelCase.php
  src/Word/SeparatorToDash.php
  src/Word/SeparatorToSeparator.php
  src/Word/UnderscoreToSeparator.php
  src/Word/UnderscoreToStudlyCase.php
  test/RealPathTest.php
  test/Word/SeparatorToCamelCaseTest.php
Labels: Documentation, Enhancement

#78 Enable Lzf, Rar and Snappy compression tests
  .laminas-ci/pre-install.sh
  psalm-baseline.xml
  src/Compress/Lzf.php
  src/Compress/Rar.php
  src/Compress/Snappy.php
  test/Compress/RarTest.php
  test/Compress/SnappyTest.php
  test/Compress/TarLoadArchiveTarTest.php
Labels: Enhancement

#80 Apply PHP 8.0 Syntax and constructor promotion
  src/AbstractDateDropdown.php
  src/AbstractFilter.php
  src/Boolean.php
  src/Compress.php
  src/Compress/AbstractCompressionAlgorithm.php
  src/Compress/Bz2.php
  src/Compress/Gz.php
  src/DataUnitFormatter.php
  src/DateTimeFormatter.php
  src/Encrypt/BlockCipher.php
  src/FilterChain.php
  src/FilterPluginManager.php
  src/FilterPluginManagerFactory.php
  src/Inflector.php
  src/PregReplace.php
  src/RealPath.php
  src/StaticFilter.php
  src/StripTags.php
  src/UriNormalize.php
  src/Word/SeparatorToCamelCase.php
  src/Word/Service/SeparatorToSeparatorFactory.php
  test/File/RenameUploadTest.php
  test/FilterPluginManagerFactoryTest.php
  test/InflectorTest.php
  test/RealPathTest.php
  test/StaticAnalysis/PluginRetrievalTest.php
  test/StaticFilterTest.php
  test/ToNullTest.php
Labels: Enhancement, dependencies

#81 Deprecate `lzf`, `rar` and `snappy` compression adapters
  .laminas-ci/pre-install.sh
  docs/book/standard-filters.md
  psalm-baseline.xml
  src/Compress/Lzf.php
  src/Compress/Rar.php
  src/Compress/Snappy.php
Labels: Documentation, Feature Removal

#83 Correct documentation callout format for deprecated adapters
  docs/book/standard-filters.md
Labels: Documentation

#86 Update standard-filters' Disable Casting table
  docs/book/standard-filters.md
Labels: Bug, Documentation

#87 Merge 2.28.1 into 2.29.x
  docs/book/standard-filters.md
Labels: Bug, Documentation
