Repository laminas/laminas-filter, pull requests merged in 2023-11, with the labels that each got.

#112 Mark all filters as `@final` where possible
  psalm-baseline.xml
  src/AllowList.php
  src/BaseName.php
  src/Boolean.php
  src/Callback.php
  src/Compress/Bz2.php
  src/Compress/Gz.php
  src/Compress/Tar.php
  src/Compress/Zip.php
  src/DataUnitFormatter.php
  src/DateSelect.php
  src/DateTimeFormatter.php
  src/DateTimeSelect.php
  src/Decompress.php
  src/DenyList.php
  src/Digits.php
  src/Dir.php
  src/Encrypt.php
  src/File/Decrypt.php
  src/File/Encrypt.php
  src/File/LowerCase.php
  src/File/Rename.php
  src/File/UpperCase.php
  src/HtmlEntities.php
  src/Inflector.php
  src/MonthSelect.php
  src/PregReplace.php
  src/RealPath.php
  src/StringPrefix.php
  src/StringSuffix.php
  src/StringTrim.php
  src/StripNewlines.php
  src/StripTags.php
  src/ToFloat.php
  src/ToInt.php
  src/ToNull.php
  src/UriNormalize.php
  src/Word/CamelCaseToDash.php
  src/Word/CamelCaseToUnderscore.php
  src/Word/DashToCamelCase.php
  src/Word/DashToSeparator.php
  src/Word/DashToUnderscore.php
  src/Word/SeparatorToDash.php
  src/Word/Service/SeparatorToSeparatorFactory.php
  src/Word/UnderscoreToDash.php
  src/Word/UnderscoreToStudlyCase.php
  test/File/RenameTest.php
Labels: Enhancement

#114 Require `laminas-i18n` in dev
  composer.json
  composer.lock
  psalm-baseline.xml
Labels: Enhancement

#115 Adds PHP 8.3 as new supported version
  .laminas-ci.json
  composer.json
  composer.lock
  psalm-baseline.xml
  test/Compress/TarTest.php
  test/InflectorTest.php
  test/Word/CamelCaseToSeparatorNoPcreUnicodeTest.php
Labels: Enhancement

#111 Add `mixed` parameter and return types to `FilterInterface`
  composer.json
  composer.lock
  psalm-baseline.xml
  src/AbstractDateDropdown.php
  src/AbstractFilter.php
  src/AbstractUnicode.php
  src/AllowList.php
  src/BaseName.php
  src/Boolean.php
  src/Callback.php
  src/Compress.php
  src/DataUnitFormatter.php
  src/DateSelect.php
  src/DateTimeFormatter.php
  src/DateTimeSelect.php
  src/Decompress.php
  src/DenyList.php
  src/Digits.php
  src/Dir.php
  src/File/LowerCase.php
  src/File/Rename.php
  src/File/RenameUpload.php
  src/File/UpperCase.php
  src/FilterChain.php
  src/FilterInterface.php
  src/HtmlEntities.php
  src/Inflector.php
  src/MonthSelect.php
  src/PregReplace.php
  src/RealPath.php
  src/StringPrefix.php
  src/StringSuffix.php
  src/StringToLower.php
  src/StringToUpper.php
  src/StringTrim.php
  src/StripNewlines.php
  src/StripTags.php
  src/ToFloat.php
  src/ToInt.php
  src/ToNull.php
  src/UpperCaseWords.php
  src/UriNormalize.php
  src/Word/AbstractSeparator.php
  src/Word/CamelCaseToSeparator.php
  src/Word/DashToSeparator.php
  src/Word/SeparatorToCamelCase.php
  src/Word/SeparatorToSeparator.php
  src/Word/UnderscoreToStudlyCase.php
  test/AbstractUnicodeTest.php
  test/TestAsset/LowerCase.php
  test/TestAsset/StripUpperCase.php
Labels: BC Break, Enhancement

#113 Adds parameter and return types to Compress filter
  psalm-baseline.xml
  src/Compress.php
  src/Compress/AbstractCompressionAlgorithm.php
  test/CompressTest.php
Labels: BC Break, Enhancement

#117 Mark all classes as `final`
  docs/book/v3/migration/v2-to-v3.md
  src/AllowList.php
  src/BaseName.php
  src/Boolean.php
  src/Callback.php
  src/Compress/Bz2.php
  src/Compress/Gz.php
  src/Compress/Tar.php
  src/Compress/Zip.php
  src/DataUnitFormatter.php
  src/DateSelect.php
  src/DateTimeFormatter.php
  src/DateTimeSelect.php
  src/Decompress.php
  src/DenyList.php
  src/Digits.php
  src/Dir.php
  src/File/LowerCase.php
  src/File/Rename.php
  src/File/UpperCase.php
  src/FilterChain.php
  src/FilterPluginManager.php
  src/HtmlEntities.php
  src/Inflector.php
  src/MonthSelect.php
  src/PregReplace.php
  src/RealPath.php
  src/StringPrefix.php
  src/StringSuffix.php
  src/StringTrim.php
  src/StripNewlines.php
  src/StripTags.php
  src/ToFloat.php
  src/ToInt.php
  src/ToNull.php
  src/UriNormalize.php
  src/Word/CamelCaseToDash.php
  src/Word/CamelCaseToUnderscore.php
  src/Word/DashToCamelCase.php
  src/Word/DashToSeparator.php
  src/Word/DashToUnderscore.php
  src/Word/SeparatorToDash.php
  src/Word/Service/SeparatorToSeparatorFactory.php
  src/Word/UnderscoreToDash.php
  src/Word/UnderscoreToStudlyCase.php
Labels: BC Break, Documentation, Enhancement
