Repository laminas/laminas-filter, pull requests merged in 2024-11, with the labels that each got.

#190 Update to latest PHP 8.1 syntax
  psalm-baseline.xml
  src/AbstractFilter.php
  src/Compress/Zip.php
  src/FilterChain.php
  src/ForceUriScheme.php
  test/CallbackTest.php
  test/FilterPluginManagerCompatibilityTest.php
  test/StaticAnalysis/PluginRetrieval.php
Labels: Enhancement

#191 Update to latest PHPUnit 10 syntax
  psalm-baseline.xml
  test/StringToLowerTest.php
Labels: Enhancement

#186 Refactor CamelCaseToSeparator Filter
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/word.md
  psalm-baseline.xml
  src/Word/CamelCaseToDash.php
  src/Word/CamelCaseToSeparator.php
  src/Word/CamelCaseToUnderscore.php
  test/Word/CamelCaseToSeparatorTest.php
  test/Word/CamelCaseToUnderscoreTest.php
Labels: BC Break, Documentation, Enhancement

#192 Refactor UnderscoreToStudlyCase Filter
  docs/book/v3/word.md
  psalm-baseline.xml
  src/Word/UnderscoreToStudlyCase.php
Labels: BC Break, Documentation, Enhancement

#193 Refactor SeparatorToSeparator Filter
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/word.md
  psalm-baseline.xml
  src/FilterPluginManager.php
  src/Word/DashToUnderscore.php
  src/Word/SeparatorToDash.php
  src/Word/SeparatorToSeparator.php
  src/Word/Service/SeparatorToSeparatorFactory.php
  src/Word/UnderscoreToDash.php
  src/Word/UnderscoreToSeparator.php
  test/FilterPluginManagerTest.php
  test/Word/SeparatorToDashTest.php
  test/Word/SeparatorToSeparatorTest.php
  test/Word/UnderscoreToSeparatorTest.php
Labels: BC Break, Documentation, Enhancement

#194 Remove `AbstractSeparator` and refactor descendants
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/word.md
  psalm-baseline.xml
  src/Word/AbstractSeparator.php
  src/Word/DashToCamelCase.php
  src/Word/SeparatorToCamelCase.php
  src/Word/UnderscoreToCamelCase.php
  src/Word/UnderscoreToStudlyCase.php
  test/Word/SeparatorToCamelCaseTest.php
Labels: BC Break, Enhancement

#199 Apply one line per sentence style to md files
  docs/book/v2/file.md
  docs/book/v2/filter-chains.md
  docs/book/v2/inflector.md
  docs/book/v2/intro.md
  docs/book/v2/migration/preparing-for-v3.md
  docs/book/v2/standard-filters.md
  docs/book/v2/static-filter.md
  docs/book/v2/word.md
  docs/book/v2/writing-filters.md
Labels: Documentation, Enhancement

#201 Fix broken links in migration guide and update relative links
  docs/book/v2/file.md
  docs/book/v3/file.md
  docs/book/v3/migration/v2-to-v3.md
Labels: Bug, Documentation
