Repository laminas/laminas-filter, pull requests merged in 2024-09, with the labels that each got.

#160 Refactor `DateTimeFormatter` Filter
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/DateTimeFormatter.php
  test/DateTimeFormatterTest.php
Labels: BC Break, Documentation, Enhancement

#161 Refactor `Digits` Filter
  psalm-baseline.xml
  src/Digits.php
  test/DigitsTest.php
Labels: BC Break, Enhancement

#162 Refactor `StringTrim` Filter
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/StringTrim.php
  test/StringTrimTest.php
Labels: BC Break, Enhancement

#164 Add installation guide placeholder for v3
  docs/book/v3/installation.md
  mkdocs.yml
Labels: Documentation, Enhancement

#165 Convert blockquotes to admonitions/call-outs
  docs/book/v3/file.md
  docs/book/v3/inflector.md
  docs/book/v3/standard-filters.md
Labels: Documentation, Enhancement

#167 Refactor `StripNewlines` filter
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/ScalarOrArrayFilterCallback.php
  src/StripNewlines.php
  test/ScalarOrArrayFilterCallbackTest.php
  test/StripNewlinesTest.php
  test/TestAsset/StringableObject.php
Labels: BC Break, Documentation, Enhancement

#168 Deprecate `AbstractFilter`
  docs/book/v2/migration/preparing-for-v3.md
  psalm-baseline.xml
  src/AbstractFilter.php
Labels: Documentation, Feature Removal

#169 Refactor `StringPrefix` and `StringSuffix` Filters
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/StringPrefix.php
  src/StringSuffix.php
  test/StringPrefixTest.php
  test/StringSuffixTest.php
Labels: BC Break, Documentation, Enhancement

#166 Add new "Basic Usage" and "Application Integration" sections
  docs/book/v3/application-integration/providing-filters-via-modules.md
  docs/book/v3/basic-usage.md
  docs/book/v3/intro.md
  mkdocs.yml
Labels: Documentation, Enhancement

#172 Refactor `ToNull`
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/ToNull.php
  test/ToNullTest.php
Labels: BC Break, Documentation, Enhancement

#171 Refactor `ToInt` & `ToFloat` Filters
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/ToFloat.php
  src/ToInt.php
  test/ToFloatTest.php
  test/ToIntTest.php
Labels: BC Break, Documentation, Enhancement

#170 Deprecate Setters & Getters for `StringPrefix` and `StringSuffix`
  psalm-baseline.xml
  src/StringPrefix.php
  src/StringSuffix.php
Labels: Documentation, Feature Removal

#174 refactor `DenyList` filter
  psalm-baseline.xml
  src/DenyList.php
  test/DenyListTest.php
Labels: BC Break, Enhancement

#175 Add missing migration docs for `DenyList`
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation

#176 Deprecations for `DenyList`
  psalm-baseline.xml
  src/DenyList.php
Labels: Documentation, Feature Removal

#179 `PregReplace` Deprecations
  psalm-baseline.xml
  src/PregReplace.php
Labels: Documentation, Feature Removal

#178 Refactor `PregReplace` filter
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/PregReplace.php
  test/FilterPluginManagerCompatibilityTest.php
  test/InflectorTest.php
  test/PregReplaceTest.php
Labels: BC Break, Documentation, Enhancement
