Repository laminas/laminas-filter, pull requests merged in 2024-04, with the labels that each got.

#131 Remove the `UriNormalize` filter
  composer.json
  composer.lock
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/FilterPluginManager.php
  src/UriNormalize.php
  test/UriNormalizeTest.php
Labels: BC Break, Feature Removal

#134 Remove dev dependency on `laminas-i18n`
  composer.json
  composer.lock
  src/FilterPluginManager.php
  test/FilterPluginManagerCompatibilityTest.php
Labels: BC Break, Feature Removal, dependencies

#133 Add a `ForceUriScheme` filter to ease removal of `UriNormalize` filter
  docs/book/v2/standard-filters.md
  psalm-baseline.xml
  src/FilterPluginManager.php
  src/ForceUriScheme.php
  test/ForceUriSchemeTest.php
Labels: Enhancement

#135 Add Roave BC Check to CI
  .laminas-ci.json
Labels: Enhancement

#132 Deprecate the `UriNormalize` filter
  docs/book/v2/migration/preparing-for-v3.md
  docs/book/v2/standard-filters.md
  mkdocs.yml
  psalm-baseline.xml
  src/UriNormalize.php
  test/UriNormalizeTest.php
Labels: Feature Removal

#128 Factory cleanup
  psalm-baseline.xml
  src/AbstractDateDropdown.php
  src/DateTimeSelect.php
  src/Decompress.php
  src/FilterPluginManagerFactory.php
  src/Word/Service/SeparatorToSeparatorFactory.php
  test/FilterPluginManagerFactoryTest.php
Labels: BC Break, Enhancement

#137 Adds missing installation page to documentation
  docs/book/v2/installation.md
  mkdocs.yml
Labels: Bug, Documentation

#139 Add deprecation notice for StaticFilter to the docs
  docs/book/v2/intro.md
  docs/book/v2/static-filter.md
Labels: Documentation, Enhancement
