Repository laminas/laminas-filter, pull requests merged in 2024-12, with the labels that each got.

#202 Remove sections on Alnum, Alpha, NumberFormat, and NumberParse
  docs/book/v3/filter-chains.md
  docs/book/v3/inflector.md
  docs/book/v3/standard-filters.md
Labels: Documentation, Enhancement

#203 Deprecate legacy compression related adapters and filters
  psalm-baseline.xml
  src/Compress.php
  src/Compress/AbstractCompressionAlgorithm.php
  src/Compress/Bz2.php
  src/Compress/CompressionAlgorithmInterface.php
  src/Compress/Gz.php
  src/Compress/Tar.php
  src/Compress/Zip.php
  src/Decompress.php
Labels: Documentation, Feature Removal

#200 Refactor `MonthSelect` removing inheritance and improving tests
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  src/MonthSelect.php
  test/MonthSelectTest.php
Labels: Enhancement

#207 Refactor DateSelect
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  src/DateSelect.php
  test/DateSelectTest.php
Labels: Enhancement

#209 Refactor DateTimeSelect
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/AbstractDateDropdown.php
  src/DateTimeSelect.php
  test/DateTimeSelectTest.php
Labels: Enhancement

#208 Refactor `FilterChain`
  docs/book/v3/filter-chains.md
  docs/book/v3/writing-filters.md
  psalm-baseline.xml
  src/FilterChain.php
  src/FilterChainFactory.php
  src/FilterChainInterface.php
  src/FilterPluginManager.php
  src/ImmutableFilterChain.php
  src/ImmutableFilterChainFactory.php
  test/FilterChainFactoryTest.php
  test/FilterChainTest.php
  test/ImmutableFilterChainFactoryTest.php
  test/ImmutableFilterChainTest.php
Labels: BC Break, Enhancement

#210 Filter Chain Deprecations
  psalm-baseline.xml
  src/FilterChain.php
Labels: Feature Removal

#211 `SeparatorToSeparator` Deprecations
  psalm-baseline.xml
  src/Word/SeparatorToSeparator.php
  src/Word/Service/SeparatorToSeparatorFactory.php
Labels: Feature Removal
