Repository laminas/laminas-filter, pull requests merged in 2024-10, with the labels that each got.

#182 Update Laminas Coding Standard to 3.0
  composer.json
  composer.lock
  phpcs.xml
  src/Boolean.php
  src/Inflector.php
Labels: Enhancement

#181 Initial PHP 8.4 Support
  .laminas-ci.json
  composer.json
  composer.lock
Labels: Enhancement

#184 Refactor `DashToSeparator` Filter
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/word.md
  src/Word/DashToSeparator.php
  test/Word/DashToSeparatorTest.php
Labels: BC Break, Documentation, Enhancement

#185 Deprecate AbstractSeparator setSeparator and getSeparator
  psalm-baseline.xml
  src/Word/AbstractSeparator.php
Labels: Documentation, Feature Removal
