Repository laminas/laminas-filter, pull requests merged in 2025-04, with the labels that each got.

#237 Refactor documentation for word filters
  docs/book/v3/word.md
Labels: Documentation, Enhancement

#240 Add `ToEnum` filter
  docs/book/v3/standard-filters.md
  src/FilterPluginManager.php
  src/ToEnum.php
  test/ToEnum/BasicEnum.php
  test/ToEnum/IntEnum.php
  test/ToEnum/StringEnum.php
  test/ToEnumTest.php
Labels: Enhancement

#241 Cast values of an iterable recursive to an string
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  src/ToString.php
  test/ToStringTest.php
Labels: Enhancement

#242 Improve "Writing Filters" docs
  docs/book/v3/writing-filters.md
Labels: Documentation

#243 Document removal of `AbstractFilter`
  docs/book/v3/migration/refactoring-from-abstract-filter.md
  docs/book/v3/migration/v2-to-v3.md
  mkdocs.yml
Labels: Documentation

#244 Document removal of `Word\AbstractSeparator`
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation

#245 Amend "final by default" documentation
  docs/book/v3/migration/v2-to-v3.md
Labels: Documentation

#247 Add documentation for new Compress/Decompress filter options
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
Labels: Documentation, Enhancement

#249 Minor Docs Improvements
  docs/book/v3/migration/v2-to-v3.md
  src/FilterChain.php
  src/FilterChainInterface.php
  src/FilterPluginManager.php
  src/ImmutableFilterChain.php
Labels: Documentation, Enhancement
