Repository laminas/laminas-filter, pull requests merged in 2025-01, with the labels that each got.

#212 Refactor RenameTest
  psalm-baseline.xml
  test/File/RenameTest.php
Labels: Enhancement

#217 StripTags filter deprecations
  psalm-baseline.xml
  src/StripTags.php
Labels: Documentation, Feature Removal

#214 Refactor StripTags filter to implement FlterInterface
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/StripTags.php
  test/FilterChainTest.php
  test/StripTagsTest.php
Labels: Enhancement

#204 Deprecate `FilterProviderInterface`
  src/FilterProviderInterface.php
  src/Module.php
Labels: Feature Removal

#205 Remove `FilterProviderInterface`
  docs/book/v3/application-integration/providing-filters-via-modules.md
  docs/book/v3/migration/v2-to-v3.md
  psalm-baseline.xml
  src/FilterProviderInterface.php
  src/Module.php
Labels: BC Break, Feature Removal

#218 Deprecate getters and setters in the `HtmlEntities` filter
  psalm-baseline.xml
  src/HtmlEntities.php
Labels: Documentation, Feature Removal

#220 Refactor Inflector Filter
  docs/book/v3/inflector.md
  docs/book/v3/migration/v2-to-v3.md
  psalm-baseline.xml
  src/FilterPluginManager.php
  src/Inflector.php
  src/InflectorFactory.php
  test/FilterPluginManagerCompatibilityTest.php
  test/InflectorFactoryTest.php
  test/InflectorTest.php
  test/TestAsset/Alpha.php
  test/TestAsset/InMemoryContainer.php
Labels: BC Break, Documentation, Enhancement, Feature Removal

#221 Inflector Filter Deprecations
  psalm-baseline.xml
  src/Inflector.php
Labels: Documentation, Feature Removal

#215 Refactor htmlentities filter
  docs/book/v3/migration/v2-to-v3.md
  docs/book/v3/standard-filters.md
  psalm-baseline.xml
  src/HtmlEntities.php
  test/HtmlEntitiesTest.php
Labels: Enhancement

#216 Refactor Dir filter to implement FlterInterface
  docs/book/v3/migration/v2-to-v3.md
  psalm-baseline.xml
  src/Dir.php
  test/DirTest.php
Labels: Enhancement
