Repository laminas/laminas-filter, pull requests merged in 2025-03, with the labels that each got.

#231 Fix baselined issues in `DenyListTest`
  psalm-baseline.xml
  test/DenyListTest.php
Labels: QA

#232 Introduce Composer Require Checker along with a Makefile
  .gitattributes
  .github/workflows/continuous-integration.yml
  .laminas-ci.json
  Makefile
  composer.json
  composer.lock
  tools/crc/.gitignore
  tools/crc/composer.json
  tools/crc/composer.lock
  tools/crc/config.json
Labels: QA

#222 Refactor Rename
  psalm-baseline.xml
  src/File/Rename.php
  test/File/RenameTest.php
Labels: BC Break, Enhancement

#234 Improve deprecation messages in `FilterChain`
  src/FilterChain.php
Labels: Documentation, Enhancement

#235 Fix PHP warnings calling `rmdir` on non-empty directories in tests. Refresh Dependencies
  composer.json
  composer.lock
  test/File/RenameTest.php
Labels: QA
